name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore allure-testops-demo/allure-testops-demo.csproj
    
    - name: Build
      run: dotnet build allure-testops-demo/allure-testops-demo.csproj --no-restore
    
    - name: Test
      run: dotnet test allure-testops-demo/allure-testops-demo.csproj --logger:"console;verbosity=detailed" --no-build --verbosity normal
      
    - name: Upload Allure results
      run: |
        for file in bin/Debug/net9.0/allure-results/*; do
          curl -X POST "https://kovalenkomykola.testops.cloud/api/rs/testresult" \
            -H "Authorization: Api-Token 0306cc1f-461b-4ff2-aee3-1ff26bc00ded" \
            -F "projectId=1" \
            -F "files[]=@$file"
        done